server:
  port: 8001

spring:
  profiles:
    active: enterprise
  ## 应用程序名称
  application:
    name: cloud-payment-service
  ## druid数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2024?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: nopassword

mybatis:
  ## 标注mybatis-mapper位置,用于让spring扫描mapper文件作为bean进行惯例
  ## 标注mapper.xml的位置,帮助mybatis管理对应的mapper.xml文件
  mapper-locations: classpath:mapper/*.xml
  ## 标注实体类所在包 mybatis扫描后 使用相应包内的类不需要写全类的限定名
  type-aliases-package: com.atguigu.cloud.entities
  configuration:
    ## 默认将数据库的字段进行驼峰命名处理
    map-underscore-to-camel-case: true

